### ISSUE TITLE
SEP 10, Error Retrieving JWT 

### ISSUE THREAD

**Issue by christopherkarani** [Soneso/stellar-ios-mac-sdk#149]
When using WebAuthenticator, and the jwtToken Method. I get the error: 

RequestError(stellarsdk.HorizonRequestError.badRequest(message: "{\"error\":\"\'transaction\' is required\"}", horizonErrorResponse: nil))

Am I the only one experiencing this issue?

**Comment by christopherkarani** [comment]
@christian-rogobete  
Not Yet, 
Im currently testing with the test Anchor (https://testanchor.stellar.org),
Im using the latest version of the sdk, and doing everything right according to SEP 10, 
Is there any more information I can provide that would help with diagnosis?

Thanks @christian-rogobete

**Comment by christian-rogobete** [comment]
Hello @christopherkarani,

thank you for the helpful info. I will check it this week with the stellar test anchor and I will let you know.

**Comment by christian-rogobete** [comment]
fixed in [release 2.4.2](https://github.com/Soneso/stellar-ios-mac-sdk/releases/tag/2.4.2). content type was missing in the post request. also added a new [remote web auth testcase](https://github.com/Soneso/stellar-ios-mac-sdk/blob/master/stellarsdk/stellarsdkTests/web_authenticator/WebAuthRemoteTestCase.swift) and updated the doc.
