### ISSUE TITLE
Decoding problem

### ISSUE THREAD

**Issue by ghost** [Soneso/stellar-ios-mac-sdk#33]
Hi, would like to clarify one point. I have an issue with the recovery of unsigned tranasction for signature. Such transaction is formed on backend NodeJS. Then it coordinates to toEnvelop, ten to xdr and finally to  base64. How can I properly restore signTX on my swift 4.2 and send it?

This from backend.
![2018-11-15 16 40 46](https://user-images.githubusercontent.com/44780996/48559898-4100c080-e8f5-11e8-8d78-bbadc9fd4d1d.jpg)

Response:
<img width="1446" alt="screen shot 2018-11-15 at 4 23 21 pm" src="https://user-images.githubusercontent.com/44780996/48559983-7e654e00-e8f5-11e8-84b5-1bc1ce8e4cdd.png">

**Comment by chelemen-razvan** [comment]
You can use the `xdr` initializer:
`let envelope = try! TransactionEnvelopeXDR(xdr: <your_xdr_string_from_backend>)`
And to send it you can just use the same string:
`StellarSDK().transactions.postTransaction(transactionEnvelope: xdr, response: { (response) -> (Void) in
            switch response {
            case .success(_):
                print("All good")
            case .failure(let error):
                print("Something went wrong")
            }
        })`

**Comment by svenPepsi** [comment]
@chelemen-razvan 
Thank you very much for the answer, can you please tell me how to make signTX (sign the transaction) and return the answer to the backend, I'm confused, sorry. I looked into the documentation, and got confused because I am doing a transaction through the backend.
I take these steps:
<img width="571" alt="screen shot 2018-11-16 at 11 33 57 am" src="https://user-images.githubusercontent.com/44780996/48613115-85429e00-e993-11e8-8e41-bfa10d3051b9.png">
Thank!

**Comment by chelemen-razvan** [comment]
Please check #34 . Seems similar with that you're trying to do.

**Comment by svenPepsi** [comment]
@chelemen-razvan Thank!
