### ISSUE TITLE
Price.fromString appears to be inaccurate

### ISSUE THREAD

**Issue by p3scobar** [Soneso/stellar-ios-mac-sdk#38]
I'm trying to construct a price for a ManageOfferOperation by passing a string to Price.fromString(price), but the return value is negative.

In the case where I pass "7.76" the return values are {-2147483648, -2147483648} when they should be {194,25}. 

I see code comments that state the function gives "unexpected results", and suggests initializing a price by passing a numerator & denominator instead. If you want to bid 7.76 for an asset, how would you know to pass {194, 25} if the fromString method gives inaccurate results?

**Comment by ndizazzo** [comment]
This doesn't directly answer your question - but the way I tackle pricing a trade is slightly different than providing the rate at which you're trading two asset pairs. 

You have a source asset, and a destination asset. For most people, it's easier to think of how much of a certain asset they want to sell, and how much of another they wish to buy. This naturally gives you the numerator and denominator of your rate as `buyingAmount / sellingAmount`. Switching your UX to require input in rational terms might not work for your use case, but might be worth considering? 

Otherwise, there's a few other [rational approximation](https://stackoverflow.com/a/35895607) Swift methods available on Stack Overflow... if you try out the sample and find that it works better - maybe a PR with an update might benefit the project.
