### ISSUE TITLE
issue on getAccountDetails and getPayments.

### ISSUE THREAD

**Issue by wixvii** [Soneso/stellar-ios-mac-sdk#49]
Hey, 
When I try to get account details and payments it is giving this error. 
"The operation couldn’t be completed. (stellarsdk.HorizonRequestError error 4.)
error!"

version: "1.6.0"

**Comment by ndizazzo** [comment]
Hey @wixvii - can you provide the code you're using (along with the account ID you're requesting), or a sample code snippet that generates the same failure?

**Comment by wixvii** [comment]
here is my code:
`        sdk.accounts.getAccountDetails(accountId: accountId) { (accountResponse) -> (Void) in
            switch accountResponse
            {
            case .success(let account):
                print(account)
            case .failure(let error):
                print(error.localizedDescription)
            }
        }`

and sample account is yours account for donate :)
"GANSYJ64BTHYFM6BAJEWXYLVSZVSHYZFPW4DIQDWJL5BOT6O6GUE7JM5"

**Comment by ndizazzo** [comment]
Which URL did you configure the SDK object with? The follow snippet (which is close to yours) yields the correct response...

```swift
let sdk = StellarSDK.init(withHorizonUrl: "https://horizon.stellar.org")
let account = "GANSYJ64BTHYFM6BAJEWXYLVSZVSHYZFPW4DIQDWJL5BOT6O6GUE7JM5"

sdk.accounts.getAccountDetails(accountId: account) { response -> Void in
    switch response {
    case .success(let details):
        print(details.balances)
        print(details.accountId)
    case .failure(let error):
        print(error)
    }
}
```

Can you also provide the output of the following command: `cat Podfile.lock | grep stellar`?

**Comment by wixvii** [comment]
yeah its work!
Sorry its my fault, I did not think about test-live horizon sdk :( 
but maybe you can add it to readME file. default sdk is test you can add it to readME. Maybe someone like me can miss it. Thank you.

**Comment by ndizazzo** [comment]
No problem - happy it's solved!

**Comment by PavelSakhanko** [comment]
Hi, Nick, I need Your help !

I'm created account in test net and checking it - he exists.
When I using getAccountDetails with "https://horizon-testnet.stellar.org" - I have error  "The data couldn’t be read because it is missing." 
When "https://horizon.stellar.org" as in the example above - 

notFound(message: "{\n  \"type\": \"https://stellar.org/horizon-errors/not_found\",\n  \"title\": \"Resource Missing\",\n  \"status\": 404,\n  \"detail\": \"The resource at the url requested was not found.  This is usually occurs for one of two reasons:  The url requested is not valid, or no data in our database could be found with the parameters provided.\"\n}", horizonErrorResponse: Optional(<stellarsdk.NotFoundErrorResponse: 0x281e3fe30>))


my account "GB33EPYLVRLD6GTCRLSBCXET35TZKJJCQDRQZHLR5UNNNWWTHMD4IL4B".

And I using 

let sdk = StellarSDK.init(withHorizonUrl: "https://horizon.stellar.org")
let account = "GB33EPYLVRLD6GTCRLSBCXET35TZKJJCQDRQZHLR5UNNNWWTHMD4IL4B"

sdk.accounts.getAccountDetails(accountId: account) { response -> Void in
            switch response {
            case .success(let details):
                print(details.balances)
                print(details.accountId)
            case .failure(let error):
                print(error)
            }
        }

But it's not works for me. 
Thank You !

**Comment by ndizazzo** [comment]
@PavelSakhanko - your issue is that `GB33EPYLVRLD6GTCRLSBCXET35TZKJJCQDRQZHLR5UNNNWWTHMD4IL4B` exists on Testnet but not on production. Your SDK initialization seems to be configured for production based on the debug output you've provided. 

Change "https://horizon.stellar.org" to "https://horizon-testnet.stellar.org" in your SDK initialization and you'll be all set.

Testnet is a completely different Stellar environment and will not have the same accounts, ledgers, and transactions as production.
