### ISSUE TITLE
Hi! "Fee" change question! 

### ISSUE THREAD

**Issue by PavelSakhanko** [Soneso/stellar-ios-mac-sdk#74]
How I can change Fee in swift ?
in Java we have method .setOperationFee()
Thanks!

**Comment by christain-rogobete** [comment]
Hi @PavelSakhanko, thank you for your question.

the current version of the sdk uses the base fee. You can not override it in version 1.6.7. 

I added a new optional parameter to "Transaction" so that you can now pass it when building the transaction. 

Pls. see my commit 

https://github.com/Soneso/stellar-ios-mac-sdk/commit/9f2f4362a0b5ae652be526987cd8b557c16d89ab

Hope it helps. Let me know if you have any further questions.

Best
Chris.

**Comment by PavelSakhanko** [comment]
@christain-rogobete 
Thank you for help! 
Everything works perfectly! If I have questions, I will contact you. 
Best regards!
